env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'next/core-web-vitals'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  no-console: 'off'
  react/react-in-jsx-scope: 'off'
  '@typescript-eslint/no-explicit-any': 'off'
  '@next/next/no-img-element': 'off'
