name: Basic checks and tests

on: [pull_request]

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Cache NPM # leverage npm cache on repeated workflow runs if package.json didn't change
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci
      - name: Build Lerna
        run: npm run bootstrap && npm run build
      - name: Lint check
        run: npm run lint
